config/routes.rb
Rails.application.routes.draw do
  root "users#show"
  devise_for :users
  resources :users, only: [:show] do
    resources :circles, only: [:index, :new, :create]
  end

  resources :songs

  get "*all" => "application#cors_preflight_check", :constraints => { :method => "OPTIONS" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/circle.rb
class Circle < ApplicationRecord
  validates :name, presence: true
  validates :user_id, presence: true

  belongs_to :user
  has_many :users
  has_many :songs
end

app/models/circle_owner.rb
class CircleOwner < User

end

app/models/circle_roster.rb
class CircleRoster < ApplicationRecord
  belongs_to :user
  belongs_to :circle

  validates :user_id, presence: true
  validates :circle_id, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  attachment :audio, extension: ["mp3", "mp4", "m4a", "aif", "wav"]

  belongs_to :user
  belongs_to :circle

  validates :title, presence: true
  validates :rating, numericality: true
  validates :play_count, numericality: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attachment :profile_image, type: :image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, uniqueness: true, presence: true
  validates :password, presence: true

  has_many :songs
  has_many :circles

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    role == 'admin'
  end

  def circle_owner?
    role == 'circle_owner'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :current_user, :cors_preflight_check
  after_action :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  def cors_preflight_check
    if request.method == :options
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
      headers['Access-Control-Allow-Headers'] = '*'
      headers['Access-Control-Max-Age'] = '1728000'
      render :text => '', :content_type => 'text/plain'
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :profile_image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name,:last_name, :email, :password, :profile_image])
  end
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
before_action :authorize_user, except: [:index, :new, :create]

  def index
    @circles = current_user.circles
  end

  def new
    @circle = Circle.new
    @users = User.all
  end

  def create
    @circle = Circle.new(circle_params)
    @circle.user = current_user
    if @circle.save
      flash[:success] = 'Circle successfully created.'
      redirect_to circles_path
    else
      flash[:notice] = @circle.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def circle_params
    params.require(:circle).permit(:name, :user_id)
  end

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Where ya goin?!@")
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authorize_user, except: [:new, :create, :show]

  def index
    @songs = Song.all
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    @song.user = current_user
    if @song.save
      flash[:success] = 'Song has been saved.'
      redirect_to user_path(@song.user)
    else
      flash[:notice] = @song.errors.full_messages.join(', ')
      render :new
    end
  end

  def show
    @song = Song.find params[:id]
  end

  private

  def song_params
    params.require(:song).permit(:title, :audio, :rating, :play_count, :user_id)
  end

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Where ya goin?!@")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user, except: [:show]

  def show
    if user_signed_in?
      @user = current_user
      @songs = current_user.songs
    else
      redirect_to :new_user_session
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :profile_image)
  end
  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Where ya goin?!@")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/circles/index.html.erb
<div class="">

<h3>Your Circles</h3>
  <ul>
  <% @circles.each do |circle| %>
     <li> <%= circle.name %> </li>
  <% end %>
</ul>
</div>

<div class="">
  <h3>Recent Activity</h3>
</div>

<%= link_to 'Create New Circle', new_circle_path %>

app/views/circles/new.html.erb
<%= form_for @circle do |f| %>

  <div class="form">
    <%= f.label :name, 'Circle Name' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <h3>Invite Existing Users</h3>
  </div>
  <div class="form-group">
    <h3>Invite New Users</h3>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-block btn-lg btn-primary" %>
  </div>
<% end %>

app/views/circles/show.html.erb
<div class="row">
  <div class="col-sm-4">
    <h3><%= @circle.name %></h3>
    <div class="top-buffer-lg">
    </div>
    <p>
        Creator: <%= @circle.user.full_name %>
    </p>
    <ul>
      <li>List of Users with avatars</li>
    </ul>
  </div>
  <% @songs.each do |song| %>
  <div class="col-sm-8 top-buffer">
    <%= render partial: 'shared/player_no_wave', locals: { song: song } %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Songcircle</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', media: 'all' %>
    <%= yield :head %>
  </head>

  <body>
    <div class="application">
      <div class="container-fluid">
        <%= render 'shared/navbar' %>
        <% flash.each do |key, value| %>
          <%= value %>
        <% end %>

        <%= yield %>
        <footer>
          <p>Created By: <%= link_to "Russel Viola", 'https://github.com/RusselViola/songcircle/' %></p>
          <!-- <%= debug(params) if Rails.env.development? %> -->
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
      <span class="sr-only">Toggle navigation</span>
    </button>
    <a class="navbar-brand" href="/">SongCircle</a>
  </div>
  <div class="collapse navbar-collapse" id="navbar-collapse-01">
    <ul class="nav navbar-nav navbar-left">
      <% if user_signed_in? %>
        <!-- <li><%= link_to 'Users', '#' %></li> -->
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to 'Upload Song', new_song_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <%= current_user.full_name %>
                <%= image_tag(attachment_url(current_user, :profile_image, :fill, 30, 30, fallback: "no-avatar-thumb.png" ), class:"img-circle") %>
                <span class="caret"></span>
            </a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Circles", circles_path %></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_player_no_wave.html.erb
<div id="wavesurfer">
  <div id="waveform" <%= "data-url= #{attachment_url(song, :audio)}" if song.audio %> >
      <div class="progress progress-striped active" id="progress-bar">
          <div class="progress-bar progress-bar-info"></div>

  <div class="text-center">
    <div class="controls btn-group">
        <button class="btn btn-primary" data-action="back" disabled>
            <i class="glyphicon glyphicon-step-backward"></i>
        </button>

        <button class="btn btn-primary" data-action="play" disabled>
            <i class="glyphicon glyphicon-play"></i>
            /
            <i class="glyphicon glyphicon-pause"></i>
        </button>

        <button class="btn btn-primary" data-action="forth" disabled>
            <i class="glyphicon glyphicon-step-forward"></i>
        </button>

        <button class="btn btn-primary" data-action="toggle-mute" disabled>
            <i class="glyphicon glyphicon-volume-off"></i>
        </button>
    </div>
  </div>
</div>

app/views/songs/_waveform.html.erb
<div id="wavesurfer">
  <div id="waveform" <%= "data-url= #{attachment_url(song, :audio)}" if song.audio %> >
      <div class="progress progress-striped active" id="progress-bar">
          <div class="progress-bar progress-bar-info"></div>
      </div>
      <!-- Here be the waveform -->
  </div>

  <div class="text-center">
    <div class="controls btn-group">
        <button class="btn btn-primary" data-action="back" disabled>
            <i class="glyphicon glyphicon-step-backward"></i>
        </button>

        <button class="btn btn-primary" data-action="play" disabled>
            <i class="glyphicon glyphicon-play"></i>
            /
            <i class="glyphicon glyphicon-pause"></i>
        </button>

        <button class="btn btn-primary" data-action="forth" disabled>
            <i class="glyphicon glyphicon-step-forward"></i>
        </button>

        <button class="btn btn-primary" data-action="toggle-mute" disabled>
            <i class="glyphicon glyphicon-volume-off"></i>
        </button>
    </div>
  </div>
</div>

app/views/songs/new.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'songs/form' %>
<% end %>

<%= form_for @song do |f| %>

  <div class="form">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :audio, "Audio File" %>
    <%= f.attachment_field :audio, direct: true, presigned: true %>

    <progress value="0" max="100"></progress>
    <p id="file-name"></p>
  </div>

  <div class="row">
    <div class="col-sm-12 top-buffer">
      <p>Preview</p>
      <%= render partial: 'waveform', locals: { song: @song } %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-block btn-lg btn-primary" %>
  </div>
<% end %>

app/views/songs/show.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'sounds/waveform' %>
<% end %>

<div class="row">
  <div class="col-sm-4">
    <h3><%= @song.title %></h3>
    <div class="top-buffer-lg">
    </div>
    <p>
        Uploaded by: <%= link_to(@song.user.full_name, @song.user) %>
    </p>
  </div>
  <div class="col-sm-8 top-buffer">
    <%= render partial: 'waveform', locals: { song: @song } %>
  </div>
</div>

app/views/users/show.html.erb
<div id="user-show-page" class="row">
  <div id="user_show" class="row offset-2">
    <div class="col-sm-10">
      <%= attachment_image_tag(current_user, :profile_image, :fill, 300, 300, fallback: "no-avatar-large.png", class: "thumbnail") %>
        <div class="col-sm-8 top-buffer">
          <h1> <%= @user.first_name %>'s Profile </h1>
          <h6>Your info</h6>
          <li><%= @user.first_name %></li>
          <li><%= @user.email %></li>
          <li>Member since: <%= @user.created_at %></li>
      </div>
    </div>
  </div>
  <div class="col-sm-8 top-buffer">
    <h3>Current Submissions:</h3>
    <ul>
      <% @songs.each do |song| %>
        <li> <%= link_to song.title, song_path(song) %> </li>
      <% end %>
    </ul>
  </div>
</div>